In [1]:
# Importing libraries 
import pandas as pd
import pickle
import numpy as np
import os

In [2]:
# Creating path to Data Folder 
path = r'/Users/farhodfurkatov/Desktop/CF Data Immersion Achievment 4/Instacart Basket Analysis/02 Data'

In [3]:
# importing the file 
ords_prods_merge1 = pd.read_csv(os.path.join(path, 'Prepared Data', 'ords_prods_merged.csv'), index_col = False)

In [4]:
ords_prods_merge1.head()

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders

In [5]:
ords_prods_merge1.shape

(32434212, 17)

In [6]:
df = ords_prods_merge1[:1000000]

In [7]:
df.shape

(1000000, 17)

In [8]:
df.groupby('product_name')

In [9]:
df.groupby('department_id').agg({'order_number':['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [10]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

In [11]:
ords_prods_merge1['max_order'] = ords_prods_merge1.groupby(["user_id"])['order_number'].transform(np.max)

In [12]:
ords_prods_merge1.head(15)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,22

In [13]:
ords_prods_merge1.head(100)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,9
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,9
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,9
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,20
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,20
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,11
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,11
23,2497897,52,1,1,9,NaN,196,4,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,27
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,27
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,27
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,27
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,27
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,27
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,14
71,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,14
72,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,14
73,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,14
74,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,6
75,520620,120,1,3,11,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,3
76,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,3
77,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,6
78,2040988,195,1,1,14,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,58
79,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,58
80,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,58
81,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,58
82,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,58
83,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,58
84,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,58
85,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,58
86,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,58
87,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,58
88,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,58
89,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,58
90,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,70
91,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,70
92,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,51
93,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,51
94,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,8
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,22

In [14]:
pd.options.display.max_rows = None

In [15]:
ords_prods_merge1.head(100)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,10
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,10
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,10
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,10
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,10
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,10
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,10
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,10
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,10
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,10
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,22
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,22
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,22
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,22
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,22
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,9
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,9
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,9
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,33
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,20
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,20
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,11
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,11
23,2497897,52,1,1,9,NaN,196,4,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,27
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,27
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,27
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,27
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,27
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,27
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,27
30,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,27
31,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,27
32,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,27
33,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,27
34,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,27
35,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,27
36,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,27
37,3205960,67,1,3,11,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,24
38,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
39,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
40,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,24
41,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,24
42,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,24
43,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,24
44,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,24
45,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
46,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
47,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,24
48,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
49,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
50,768572,67,16,4,10,9.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,24
51,150528,67,18,5,16,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,24
52,29758,67,19,0,14,9.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
53,1558976,67,21,1,9,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
54,863974,67,22,1,11,14.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
55,2308399,67,23,1,14,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,24
56,2759128,81,3,1,9,14.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,7
57,1812985,81,5,2,20,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,7
58,1889835,82,1,3,15,NaN,196,6,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,19
59,499460,82,3,5,10,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,19
60,2728456,82,4,0,11,16.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,19
61,2653743,82,6,4,9,13.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,19
62,1358880,82,9,1,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,19
63,343588,82,10,2,11,1.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,19
64,3034663,82,15,2,11,12.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,19
65,147262,82,18,1,13,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,19
66,3144004,82,19,2,15,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,19
67,2126069,98,3,0,9,25.0,196,7,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,14
68,2210120,98,7,5,14,5.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,14
69,681011,98,9,3,9,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,14
70,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,14
71,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,14
72,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,14
73,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,14
74,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,6
75,520620,120,1,3,11,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,3
76,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,3
77,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,6
78,2040988,195,1,1,14,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,58
79,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,58
80,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,58
81,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,58
82,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest days,Most Orders,58
83,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,58
84,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,58
85,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,58
86,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,58
87,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,58
88,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,58
89,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,58
90,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,70
91,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,70
92,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,51
93,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,51
94,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,8
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Most Orders,3
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regular busy days,Average orders,3
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy days,Most Orders,8
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Busiest days,Average orders,22
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy days,Average orders,22

In [16]:
ords_prods_merge1.loc[ords_prods_merge1['max_order'] > 40, 'loyalty_flag'] = "Loyal customer"

In [17]:
ords_prods_merge1.loc[(ords_prods_merge1['max_order'] <= 40) & (ords_prods_merge1['max_order'] > 10), "loyalty_flag"] = 'Regular customer'

In [18]:
ords_prods_merge1.loc[ords_prods_merge1['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [19]:
ords_prods_merge1['loyalty_flag'].value_counts(dropna = False)

Regular customer    15891077
Loyal customer      10293737
New customer         6249398
Name: loyalty_flag, dtype: int64

In [20]:
ords_prods_merge1[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43  Regular customer             6
22       43  Regular customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3

# Task 4.8

## Step 2

In [21]:
# Looking up the mean for the whole data frame Grop by department_id
ords_prods_merge1.groupby('department_id').agg('mean')

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,aisle_id,prices,max_order
department_id,,,,,,,,,,,,
1,1.711344e+06,103197.633516,15.457687,2.790461,13.681744,11.731031,24390.198727,8.996414,0.541885,69.625666,7.741434,30.335007
2,1.715933e+06,103120.908572,17.277920,2.851368,13.498939,10.952867,27755.745006,8.277645,0.407980,6.000000,6.990934,31.908131
3,1.710748e+06,102800.045144,17.179756,2.743178,13.395367,11.095811,23853.279970,8.084397,0.628141,100.870971,7.864723,33.447622
4,1.710657e+06,102839.977379,17.811403,2.683672,13.424949,10.856212,27169.833725,8.022875,0.649913,63.624854,7.981708,34.022678
5,1.712416e+06,103923.449991,15.213779,3.163259,13.594232,10.341975,26176.170317,5.429476,0.569867,59.709073,8.144407,29.979160
6,1.707786e+06,102797.179961,16.439806,2.691937,13.518913,11.291251,23176.950964,9.947061,0.369229,55.123924,7.682264,31.589126
7,1.711080e+06,103044.251637,17.225773,2.807195,13.314118,11.053422,24975.334825,6.976057,0.653455,78.909370,7.680574,33.177384
8,1.713293e+06,103537.208076,15.340520,2.934868,13.578394,11.868070,23290.045342,7.718544,0.601285,40.648981,7.889636,29.598011
9,1.711269e+06,102960.197036,15.895474,2.690505,13.546041,11.774450,25253.734390,10.212863,0.461076,54.489774,7.350283,30.668129
10,1.717443e+06,102482.728661,20.197148,2.759061,13.458537,10.104230,18263.701501,8.399040,0.577040,42.882133,8.348960,37.891042
11,1.711393e+06,102584.318374,16.170828,2.816534,13.486789,11.593415,23979.240869,8.752646,0.321309,59.604276,7.996657,30.527567
12,1.712765e+06,102873.027888,15.887622,2.718074,13.468487,11.432038,23870.406605,8.528225,0.567674,74.888960,16.294469,31.122472
13,1.711952e+06,102961.107824,16.583304,2.810486,13.458787,11.163426,25278.561796,9.593425,0.346721,61.951483,8.009901,32.025704
14,1.709335e+06,102994.470305,16.757377,2.730050,13.332403,11.298226,26212.063522,9.125784,0.560878,106.439072,8.065461,32.792282
15,1.712026e+06,102675.749021,16.165037,2.707202,13.453348,11.656079,23392.289574,9.947258,0.457405,73.887759,7.539976,30.326645
16,1.710339e+06,103030.978502,17.663250,2.739444,13.367475,10.986297,25322.395323,7.495423,0.669969,79.198382,33.425510,34.318531
17,1.711255e+06,102865.012866,15.694469,2.835449,13.349908,11.996490,24051.306783,8.492163,0.402178,76.748621,7.384058,29.926944
18,1.706348e+06,103024.423943,19.310397,2.711004,13.397596,10.004465,25051.904109,10.575925,0.578971,89.919854,7.638380,37.881202
19,1.710089e+06,102999.937311,17.177343,2.751490,13.360846,10.947879,25380.724173,9.187743,0.574180,68.334496,4.275437,33.427779
20,1.709579e+06,102690.482049,16.473447,2.705505,13.481529,11.345655,25659.100628,8.693815,0.607719,61.769719,7.778701,32.396779
21,1.718715e+06,103210.777121,22.902379,2.800853,13.454841,10.218559,26057.782761,9.339489,0.395849,100.000000,8.660716,29.417268

## Step 3

In [22]:
# getting the mean for entire table wont make much sense as we do not need to look at the mean for all the columns 
# at the same time we can see some insigts on column prices and can see that department 16 has highest average for prices
# highest maximum orders for Department 10

## Step 4

In [23]:
# see above

## Step 5

In [24]:
# grouping customers by loyalty category and looking up some insights about their spending habits
ords_prods_merge1.groupby('loyalty_flag').agg('mean')

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,aisle_id,department_id,prices,max_order
loyalty_flag,,,,,,,,,,,,,
Loyal customer,1.710125e+06,102790.293273,32.639724,2.791603,13.188149,6.026927,25558.961411,8.282641,0.739439,71.169557,9.974806,10.388747,63.979888
New customer,1.714047e+06,103217.686411,3.806988,2.697384,13.673689,17.977110,25600.228919,8.267688,0.348286,71.340218,9.879847,13.294370,6.575013
Regular customer,1.709854e+06,102922.405466,12.347100,2.720903,13.480615,12.155304,25581.138460,8.428405,0.587621,71.198234,9.904842,12.496203,23.430697

## Step 6

In [25]:
# Grouping customers and checking how much on average they spent per item
ords_prods_merge1['spend_average'] = ords_prods_merge1.groupby(["user_id"])['prices'].transform(np.mean)

In [26]:
#creating the labesls
ords_prods_merge1.loc[ords_prods_merge1['spend_average'] >= 10 , 'spender_flag'] = "High Spender"

In [27]:
ords_prods_merge1.loc[ords_prods_merge1['spend_average'] < 10 , 'spender_flag'] = "Low Spender"

In [28]:
ords_prods_merge1['spender_flag'].value_counts(dropna = False)

Low Spender     31798879
High Spender      635333
Name: spender_flag, dtype: int64

## Step 7

In [29]:
# Grouping customers and chcking how often they order 
ords_prods_merge1['order_frequency'] = ords_prods_merge1.groupby(["user_id"])['days_since_prior_order'].transform(np.median)

In [30]:
#creating the labels
ords_prods_merge1.loc[ords_prods_merge1['order_frequency'] > 20 , 'frequency_flag'] = "Non-frequent customer"

In [31]:
ords_prods_merge1.loc[(ords_prods_merge1['order_frequency'] <= 20) & (ords_prods_merge1['order_frequency'] > 10), "frequency_flag"] = 'Regular customer'

In [32]:
ords_prods_merge1.loc[ords_prods_merge1['order_frequency'] <= 10 , 'frequency_flag'] = "Frequent customer"

In [33]:
ords_prods_merge1['frequency_flag'].value_counts(dropna = False)

Frequent customer        21577409
Regular customer          7217134
Non-frequent customer     3639669
Name: frequency_flag, dtype: int64

In [34]:
ords_prods_merge1.head(60)

,order_id,user_id,order_number,order_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,_merge,price_range_loc,busiest_days,busiest_period_of_day,max_order,loyalty_flag,spend_average,spender_flag,order_frequency,frequency_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,both,Mid-range product,Regular busy days,Average orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,both,Mid-range product,Least busy days,Average orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,both,Mid-range product,Least busy days,Most Orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,both,Mid-range product,Least busy days,Average orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,both,Mid-range product,Least busy days,Most Orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,both,Mid-range product,Regular busy days,Average orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,both,Mid-range product,Least busy days,Average orders,10,New customer,6.367797,Low Spender,20.5,Non-frequent customer
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,both,Mid-range product,Busiest days,Most Orders,22,Regular customer,3.980556,Low Spender,10.0,Frequent customer
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,22,Regular customer,3.980556,Low Spender,10.0,Frequent customer
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,22,Regular customer,3.980556,Low Spender,10.0,Frequent customer
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,22,Regular customer,3.980556,Low Spender,10.0,Frequent customer
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,22,Regular customer,3.980556,Low Spender,10.0,Frequent customer
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,both,Mid-range product,Regular busy days,Most Orders,9,New customer,8.372059,Low Spender,6.0,Frequent customer
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,9,New customer,8.372059,Low Spender,6.0,Frequent customer
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,both,Mid-range product,Least busy days,Average orders,9,New customer,8.372059,Low Spender,6.0,Frequent customer
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,both,Mid-range product,Least busy days,Most Orders,33,Regular customer,7.012683,Low Spender,7.5,Frequent customer
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,both,Mid-range product,Least busy days,Average orders,20,Regular customer,8.137793,Low Spender,6.0,Frequent customer
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,both,Mid-range product,Least busy days,Most Orders,20,Regular customer,8.137793,Low Spender,6.0,Frequent customer
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,both,Mid-range product,Least busy days,Most Orders,11,Regular customer,7.444898,Low Spender,10.0,Frequent customer
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,both,Mid-range product,Least busy days,Most Orders,11,Regular customer,7.444898,Low Spender,10.0,Frequent customer
23,2497897,52,1,1,9,NaN,196,4,0,Soda,...,both,Mid-range product,Busiest days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,both,Mid-range product,Regular busy days,Average orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
30,2542086,52,11,2,9,7.0,196,3,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
31,944694,52,12,1,16,6.0,196,7,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
32,1268191,52,15,2,11,8.0,196,3,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
33,1122089,52,17,2,10,6.0,196,4,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
34,1498922,52,18,2,10,14.0,196,6,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
35,180919,52,19,3,8,8.0,196,4,1,Soda,...,both,Mid-range product,Least busy days,Average orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
36,2695875,52,21,5,10,30.0,196,1,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,27,Regular customer,6.408876,Low Spender,8.0,Frequent customer
37,3205960,67,1,3,11,NaN,196,1,0,Soda,...,both,Mid-range product,Least busy days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
38,970922,67,2,1,15,5.0,196,2,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
39,596585,67,3,1,13,7.0,196,2,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
40,2037087,67,4,2,9,8.0,196,1,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
41,2474111,67,5,3,14,8.0,196,2,1,Soda,...,both,Mid-range product,Least busy days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
42,1568481,67,6,3,12,7.0,196,2,1,Soda,...,both,Mid-range product,Least busy days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
43,2048527,67,8,2,11,7.0,196,1,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
44,2389031,67,9,2,14,7.0,196,1,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
45,2378562,67,10,1,10,6.0,196,1,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
46,1515698,67,11,1,11,7.0,196,1,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
47,1928050,67,12,2,12,8.0,196,1,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
48,1949274,67,13,1,10,6.0,196,1,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
49,551869,67,14,1,9,7.0,196,1,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
50,768572,67,16,4,10,9.0,196,1,1,Soda,...,both,Mid-range product,Least busy days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
51,150528,67,18,5,16,4.0,196,1,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
52,29758,67,19,0,14,9.0,196,2,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
53,1558976,67,21,1,9,5.0,196,2,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
54,863974,67,22,1,11,14.0,196,3,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
55,2308399,67,23,1,14,14.0,196,1,1,Soda,...,both,Mid-range product,Busiest days,Most Orders,24,Regular customer,7.656790,Low Spender,7.0,Frequent customer
56,2759128,81,3,1,9,14.0,196,2,0,Soda,...,both,Mid-range product,Busiest days,Most Orders,7,New customer,8.262963,Low Spender,30.0,Non-frequent customer
57,1812985,81,5,2,20,30.0,196,1,1,Soda,...,both,Mid-range product,Regular busy days,Average orders,7,New customer,8.262963,Low Spender,30.0,Non-frequent customer
58,1889835,82,1,3,15,NaN,196,6,0,Soda,...,both,Mid-range product,Least busy days,Most Orders,19,Regular customer,6.441221,Low Spender,11.5,Regular customer
59,499460,82,3,5,10,5.0,196,2,1,Soda,...,both,Mid-range product,Regular busy days,Most Orders,19,Regular customer,6.441221,Low Spender,11.5,Regular customer

In [43]:
ords_prods_merge1.to_csv(os.path.join(path, 'Prepared Data', 'ords_prods_merged.csv'), index = False)

In [46]:
ords_prods_merge1.to_pickle(r'/Users/farhodfurkatov/Desktop/pickle/new_doc.pkl')

OSError: [Errno 22] Invalid argument

In [50]:
import seaborn as sns
sns.__version__

'0.8.1'

In [51]:
pip install seborn --upgrade

The following command must be run outside of the IPython shell:

    $ pip install seborn --upgrade

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more informations on how to install packages:

    https://docs.python.org/3/installing/